name: Reusable Workflow caller

on:
  workflow_dispatch:

jobs:
  passValue:
    uses: ./.github/workflows/callable.yaml
    with:
      RandomId: 1234567 
      character: asdf
  WithoutpassingValue:
    uses: ./.github/workflows/callable.yaml
