name: expressions and context Workflow
on: workflow_dispatch
jobs:
  expressionsandcontext :
    runs-on: ubuntu-latest
    steps:
      - name: Search for a String
        run: echo "${{contains('Hello world', 'llo')}}"
      - run: echo "#{{github}}"
